accent = "#FF0DC0"
cursor = "#40F1EA"
foreground = "#F772F4"
background = "#233563"
selection_foreground = "#233563"
selection_background = "#FF0DC0"

color0 = "#233563"
color1 = "#D10953"
color2 = "#6DEC99"
color3 = "#D9D63D"
color4 = "#1781E8"
color5 = "#9923FF"
color6 = "#40F1EA"
color7 = "#F772F4"
color8 = "#1781E8"
color9 = "#FF0DC0"
color10 = "#6DEC99"
color11 = "#D9D63D"
color12 = "#40F1EA"
color13 = "#F772F4"
color14 = "#40F1EA"
color15 = "#40F1EA"
